<?php

// edit the following line to point at the Wallabag database
$database="/var/www/html/wallabag/db/poche.sqlite";

$action=$_POST["action"];
$id=$_POST['id'];

echo "<form method=post style='display:inline'>";
echo "<input type=submit name=action value='top'>";
echo "</form>";
echo " ";
echo "<form method=post style='display:inline'>";
echo "<input type=submit name=action value='raw'>";
echo "</form>";
echo " ";
echo "<form method=post style='display:inline'>";
echo "<input type=submit name=action value='view'>";
echo "</form>";
echo " ";
echo "<form method=post style='display:inline'>";
echo "<input type=submit name=action value='empty bag'>";
echo "</form>";

if($action =='top') {
	$action="";
}

if($action =="empty bag") {
	$dbh=open_db($database);
	$query = "delete from bag";
	$result = $dbh->exec($query);
	close_db($dbh);
	$action="";
}

if($action =="delete") {
	$dbh=open_db($database);
	$query = "delete from bag where id='$id'";
	$result = $dbh->exec($query);
	close_db($dbh);
	$action="";
}

if($action =="") {

	$dbh=open_db($database);
	$query = "select id,title,url,user_id,stamp from bag";
	$result = $dbh->query($query);

	echo "<p><table border=0 cellpadding=2 cellspacing=2>";
	while($row = $result->fetchArray()) {
		$id=$row['id'];
		//$title=$row['title'];
		$title=preg_replace('/[^A-za-z0-9\'\"\?\.\&\!\$\:\;\/\- ]/', ' ',$row['title']);
		$url=$row['url'];
		$user_id=$row['user_id'];
		$stamp=$row['stamp'];
		echo "<tr>";
		echo "<td valign=top>$id</td>";
		echo "<td>";
		echo "<form method=post>";
		echo "<input type=hidden name=id value='$id'>";
		echo "<input type=submit name=action value='delete'>";
		echo "</form>";
		echo "</td>";
		echo "<td valign=top><a href='$url' target='_NEW$id'>$title</a></td>";
		echo "<td valign=top>($stamp)</td>";
		echo "</tr>";
	}
	echo "</table>";
	close_db($dbh);
}

if($action == "raw") {
	$now = date('Ymd');

	echo "<p><textarea rows=20 cols=80>";
	echo "What's been in my bag this week? ($now)\n\n";
	$prev="";
	$dbh=open_db($database);
	$query = "select title,url,stamp,id from bag order by stamp";
	$result = $dbh->query($query);
	while($row = $result->fetchArray()) {
		$title=preg_replace('/[^A-za-z0-9\'\"\?\.\&\!\$\:\;\/\- ]/', ' ',$row['title']);

		$url=$row['url'];
		$stamp=$row['stamp'];
		$id=$row['id'];
		if($stamp == $prev) {
		} else {
			echo "<p style='font-size:medium'>$stamp</p><p>";
		}
		echo "- <a href='$url' target='_NEW$id'>$title</a><br/>\n";
		$prev=$stamp;
	}
	echo "\n<p style='font-size:x-small'>Above was generated by a homegrown bolt-on script for <a href='https://www.wallabag.org/' target='_NEWWALLA'>Wallabag</a>, which is a free utility for capturing web content so that it can be read later.</p>";
	echo "</textarea>";
	close_db($dbh);
}

if($action == "view") {
	$now = date('Ymd');

	echo "<p>What's been in my bag this week? ($now)\n\n";
	$prev="";
	$dbh=open_db($database);
	$query = "select title,url,stamp,id from bag order by stamp";
	$result = $dbh->query($query);
	while($row = $result->fetchArray()) {
		$title=preg_replace('/[^A-za-z0-9\'\"\?\.\&\!\$\:\;\/\- ]/', ' ',$row['title']);

		$url=$row['url'];
		$stamp=$row['stamp'];
		$id=$row['id'];
		if($stamp == $prev) {
		} else {
			echo "<p style='font-size:medium'>$stamp</p><p>";
		}
		echo "- <a href='$url' target='_NEW$id'>$title</a><br/>\n";
		$prev=$stamp;
	}
	echo "\n<p style='font-size:x-small'>Above was generated by a homegrown bolt-on script for <a href='https://www.wallabag.org/' target='_NEWWALLA'>Wallabag</a>, which is a free utility for capturing web content so that it can be read later.</p>";
	close_db($dbh);
}

function open_db($database) {
	$dbh = new SQLite3($database);
	if(!$dbh) die ($error);
	return $dbh;
}

function close_db($dbh) {
	$dbh->close();
}

?>
